File path is /scratch/work/hakkina7/melanoma/
Device is cuda
Model succesfully loaded from /scratch/work/hakkina7/melanoma/inceptionV3.pth
Evaluating the inceptionV3.pth model on the test set.

##################################################################
No attack
Computing took ~1 minutes.

Classified 64.52 % of test images correctly.
##################################################################

Precision on test set: [0.39 0.64 0.34 0.27 0.55 0.83 0.49 0.64]
Recall on test set: [0.49 0.65 0.54 0.47 0.46 0.75 0.41 0.79]
F1-score on test set: [0.44 0.65 0.41 0.34 0.5  0.79 0.45 0.71]
ROC AUC on test set: {'AK': 0.67, 'BCC': 0.93, 'BKL': 0.55, 'DF': 0.59, 'MEL': 0.44, 'NV': 0.28, 'SCC': 0.71, 'VASC': 0.39}
Confusion matrix on test set:
                 pred as AK  pred as BCC  ...  pred as SCC  pred as VASC
true class AK            64           23  ...            5             0
true class BCC           34          325  ...           15             1
true class BKL           20           42  ...            4             3
true class DF             0            7  ...            0             0
true class MEL           21           32  ...           12             1
true class NV             8           63  ...            4            12
true class SCC           17           12  ...           39             0
true class VASC           0            3  ...            0            30

[8 rows x 8 columns]


##################################################################
FGM
Computing took ~1 minutes.

Classified 39.75 % of test images correctly.
##################################################################


##################################################################
PGD with 1 iterations
Computing took ~1 minutes.

Classified 38.46 % of test images correctly.
##################################################################


##################################################################
PGD with 2 iterations
Computing took ~2 minutes.

Classified 25.56 % of test images correctly.
##################################################################


##################################################################
PGD with 5 iterations
Computing took ~3 minutes.

Classified 14.92 % of test images correctly.
##################################################################


##################################################################
PGD with 10 iterations
Computing took ~5 minutes.

Classified 10.98 % of test images correctly.
##################################################################


##################################################################
PGD with 20 iterations
Computing took ~10 minutes.

Classified 9.40 % of test images correctly.
##################################################################

/home/hakkina7/.local/lib/python3.8/site-packages/torchvision/models/inception.py:81: FutureWarning: The default weight initialization of inception_v3 will be changed in future releases of torchvision. If you wish to keep the old behavior (which leads to long initialization times due to scipy/scipy#11299), please set init_weights=True.
  warnings.warn('The default weight initialization of inception_v3 will be changed in future releases of '
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [0,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [2,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [3,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [0,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "eval_inception.py", line 168, in <module>
    evaluate(model, testloader, adv='CW')
  File "eval_inception.py", line 75, in evaluate
    images = CW(model, images, n_classes=2)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/cleverhans/torch/attacks/carlini_wagner_l2.py", line 145, in carlini_wagner_l2
    logits = model_fn(new_x)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torchvision/models/inception.py", line 200, in forward
    x, aux = self._forward(x)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torchvision/models/inception.py", line 155, in _forward
    x = self.Mixed_5c(x)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torchvision/models/inception.py", line 249, in forward
    outputs = self._forward(x)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torchvision/models/inception.py", line 236, in _forward
    branch5x5 = self.branch5x5_2(branch5x5)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torchvision/models/inception.py", line 472, in forward
    x = self.conv(x)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/hakkina7/.local/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 442, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([5, 48, 35, 35], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(48, 64, kernel_size=[5, 5], padding=[2, 2], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [2, 2, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x55b9f02b0e50
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 5, 48, 35, 35, 
    strideA = 58800, 1225, 35, 1, 
output: TensorDescriptor 0x55b9f02b06c0
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 5, 64, 35, 35, 
    strideA = 78400, 1225, 35, 1, 
weight: FilterDescriptor 0x55b9f0fe9570
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 64, 48, 5, 5, 
Pointer addresses: 
    input: 0x2b3c3d299800
    output: 0x2b3c38d30800
    weight: 0x2b3bf7600000
Forward algorithm: 1

srun: error: gpu15: task 0: Exited with exit code 1
srun: launch/slurm: _step_signal: Terminating StepId=65466509.0
